services:
  admin:
    build: .
    ports:
      - 8049:80

  crate:
    image: crate:latest
    ports:
      - "4200:4200"
    command: [ "crate",
               "-Cdiscovery.type=single-node",
               "-Chttp.cors.enabled=true",
               "-Chttp.cors.allow-origin=*", # Change this to your actual (or relevant) local IP.
    ]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
    volumes:
      - crate01:/data
      - crate_backup:/data/backup

volumes:
  crate01:
  crate_backup: