services:
  admin:
    build: .
    ports:
      - 8049:80
  crate:
    image: crate:latest
    ports:
      - "4200:4200"
    command: [ "crate",
               "-Cdiscovery.type=single-node",
               "-Chttp.cors.enabled=true",
               "-Chttp.cors.allow-origin=http://localhost:8049",

    ]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - CRATE_HEAP_SIZE=2g
